import type { Ingredient } from "./types";

export interface IngredientWithPricing extends Omit<Ingredient, 'price'> {
    pricing: { [size: string]: number };
    imageUrl: string;
    type: string;
}

// Liste complète des ingrédients avec leurs prix par taille
export const INGREDIENTS_WITH_PRICING: IngredientWithPricing[] = [
    // Base offerte (prix 0 pour toutes les tailles)
    {
        id: "1",
        name: "Sauce tomate",
        pricing: { "24cm": 0, "33cm": 0, "40cm": 0 },
        imageUrl: "/images/ingredients/sauce-tomate.png",
        type: "base",
        isDefault: true,
        isAvailable: true,
    },
    {
        id: "2",
        name: "Mozzarella Fior di latte",
        pricing: { "24cm": 0, "33cm": 0, "40cm": 0 },
        imageUrl: "/images/ingredients/mozzarella.png",
        type: "base",
        isDefault: true,
        isAvailable: true,
    },
    {
        id: "23",
        name: "Origan",
        pricing: { "24cm": 0, "33cm": 0, "40cm": 0 },
        imageUrl: "/images/ingredients/origan.png",
        type: "base",
        isDefault: true,
        isAvailable: true,
    },

    // Charcuterie/viande
    {
        id: "11",
        name: "Jambon cuit",
        pricing: { "24cm": 4, "33cm": 4, "40cm": 5 },
        imageUrl: "/images/ingredients/jambon.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "33",
        name: "Poitrine dinde",
        pricing: { "24cm": 4, "33cm": 4, "40cm": 5 },
        imageUrl: "/images/ingredients/poulet.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "4",
        name: "Poulet grillé",
        pricing: { "24cm": 5, "33cm": 5, "40cm": 6 },
        imageUrl: "/images/ingredients/poulet.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "14",
        name: "Lard",
        pricing: { "24cm": 4, "33cm": 4, "40cm": 5 },
        imageUrl: "/images/ingredients/lard.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "34",
        name: "Merguez",
        pricing: { "24cm": 5, "33cm": 5, "40cm": 6 },
        imageUrl: "/images/ingredients/saucisse-epicee.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "35",
        name: "Salami piquant",
        pricing: { "24cm": 4, "33cm": 4, "40cm": 5 },
        imageUrl: "/images/ingredients/lard.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "36",
        name: "Bresaola",
        pricing: { "24cm": 6, "33cm": 6, "40cm": 8 },
        imageUrl: "/images/ingredients/pepperoni.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "37",
        name: "Jambon cru",
        pricing: { "24cm": 6, "33cm": 6, "40cm": 8 },
        imageUrl: "/images/ingredients/jambon.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "38",
        name: "Mortadella",
        pricing: { "24cm": 5, "33cm": 5, "40cm": 7 },
        imageUrl: "/images/ingredients/jambon.png",
        type: "viande",
        isDefault: false,
        isAvailable: true,
    },

    // Poisson
    {
        id: "16",
        name: "Thon",
        pricing: { "24cm": 3, "33cm": 3, "40cm": 4 },
        imageUrl: "/images/ingredients/thon.png",
        type: "poisson",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "15",
        name: "Anchois",
        pricing: { "24cm": 3, "33cm": 3, "40cm": 4 },
        imageUrl: "/images/ingredients/anchois.png",
        type: "poisson",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "8",
        name: "Saumon fumé",
        pricing: { "24cm": 6, "33cm": 6, "40cm": 8 },
        imageUrl: "/images/ingredients/salomon.png",
        type: "poisson",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "17",
        name: "Crevette",
        pricing: { "24cm": 5, "33cm": 5, "40cm": 5 },
        imageUrl: "/images/ingredients/crevette.png",
        type: "poisson",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "39",
        name: "Fruit de mer",
        pricing: { "24cm": 6, "33cm": 6, "40cm": 7 },
        imageUrl: "/images/ingredients/crevette.png",
        type: "poisson",
        isDefault: false,
        isAvailable: true,
    },

    // Légumes
    {
        id: "18",
        name: "Champignon Blanc",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/champignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "40",
        name: "Oignon rouge",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/oignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "41",
        name: "Câpres",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/oignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "42",
        name: "Artichauts",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/oignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "43",
        name: "Oeuf dur",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/champignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "44",
        name: "Olives",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/champignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "21",
        name: "Poivron",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/poivron.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "20",
        name: "Ananas",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/ananas.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "25",
        name: "Aubergine",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/aubergine.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "45",
        name: "Basilic",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/epinard.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "46",
        name: "Roquette",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/arugula.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "47",
        name: "Tomate Jaunes",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/tomate.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "24",
        name: "Tomate Cérise",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/tomate-cerise.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "32",
        name: "Épinards",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/epinard.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "48",
        name: "Pignon",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/champignon.png",
        type: "legume",
        isDefault: false,
        isAvailable: true,
    },

    // Produit laitier
    {
        id: "49",
        name: "Fromage frais",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/fromage.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "50",
        name: "Gorgonzola",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/dorblu.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "51",
        name: "Grana Padano écaille",
        pricing: { "24cm": 3, "33cm": 3, "40cm": 3 },
        imageUrl: "/images/ingredients/fromage.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "5",
        name: "Ricotta",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/ricotta.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "52",
        name: "Mozzarella di Bufala",
        pricing: { "24cm": 3, "33cm": 3, "40cm": 5 },
        imageUrl: "/images/ingredients/fromage.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "53",
        name: "Burrata",
        pricing: { "24cm": 4, "33cm": 4, "40cm": 6 },
        imageUrl: "/images/ingredients/fromage.png",
        type: "fromage",
        isDefault: false,
        isAvailable: true,
    },

    // Huile
    {
        id: "54",
        name: "Huile de Truffe",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/champignon.png",
        type: "huile",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "55",
        name: "Huile à l'ail",
        pricing: { "24cm": 1, "33cm": 1, "40cm": 1 },
        imageUrl: "/images/ingredients/ail.png",
        type: "huile",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "56",
        name: "Pesto basilic",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/epinard.png",
        type: "huile",
        isDefault: false,
        isAvailable: true,
    },
    {
        id: "57",
        name: "Pesto pistache",
        pricing: { "24cm": 2, "33cm": 2, "40cm": 2 },
        imageUrl: "/images/ingredients/epinard.png",
        type: "huile",
        isDefault: false,
        isAvailable: true,
    },
]; 